// <auto-generated />
using ChessAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessAPI.Migrations
{
    [DbContext(typeof(ChessAPIDBContext))]
    partial class ChessAPIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");
            modelBuilder.Entity("ChessAPI.Models.GameMove", b =>
            {
                b.Property<string>("gameId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("move")
                    .HasColumnType("TEXT");

                b.ToTable("GameMoves");
            });

            modelBuilder.Entity("ChessAPI.Models.GameRecord", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("gameId")
                    .HasColumnType("TEXT");

                b.Property<string>("lastMovePlayer1")
                    .HasColumnType("TEXT");

                b.Property<string>("lastMovePlayer2")
                    .HasColumnType("TEXT");

                b.Property<string>("player1")
                    .HasColumnType("TEXT");

                b.Property<string>("player2")
                    .HasColumnType("TEXT");

                b.Property<string>("state")
                    .HasColumnType("TEXT");

                b.HasKey("id");

                b.ToTable("GameRecords");
            });

            modelBuilder.Entity("ChessAPI.Models.Order", b =>
            {
                b.Property<string>("productId")
                    .HasColumnType("TEXT");

                b.Property<string>("userName")
                    .HasColumnType("TEXT");

                b.ToTable("Orders");
            });

            modelBuilder.Entity("ChessAPI.Models.User", b =>
            {
                b.Property<string>("userName")
                    .HasColumnType("TEXT");

                b.Property<string>("address")
                    .HasColumnType("TEXT");

                b.Property<string>("password")
                    .HasColumnType("TEXT");

                b.HasKey("userName");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
